<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="files\pico.min.css">
    <title>Report: Example-Pkg-Your-Username-Here, Version: 22.4.8</title>
  </head>
  <body>
    <main class="container">
        <hgroup>
            <h1 id="top">Example-Pkg-Your-Username-Here </h1> 
            <h2>Version: 22.4.8<br/>Generated on: 2022-04-23 22:44:26+02:00</h2>
        </hgroup>
        <nav>
            <ul>
                    <li><a href="#Versions">Versions (4)</a></li>
                    <li><a href="#Test">Test (25%)</a></li>
                    <li><a href="#Documentation">Documentation (69%)</a></li>
                    <li><a href="#Dependencies">Dependencies (11)</a></li>
                    <li><a href="#Security">Security (2)</a></li>
                    <li><a href="#Style">Style (2)</a></li>
                    <li><a href="#Types">Types (1)</a></li>
            </ul>
        </nav>

    
        
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Versions">Versions</h2>
                            <h3>Tested Dependency Combinations: 4</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <details>
                                <summary>Python 3.9, Python-dateutil 2.8: Success</summary>
                                <p>All tests passed with Python 3.9, Python-dateutil 2.8.</p>
                            </details>
                        
                            <details>
                                <summary>Python 3.9, Python-dateutil 2.7: Success</summary>
                                <p>All tests passed with Python 3.9, Python-dateutil 2.7.</p>
                            </details>
                        
                            <details>
                                <summary>Python 3.10, Python-dateutil 2.8: Success</summary>
                                <p>All tests passed with Python 3.10, Python-dateutil 2.8.</p>
                            </details>
                        
                            <details>
                                <summary>Python 3.10, Python-dateutil 2.7: Success</summary>
                                <p>All tests passed with Python 3.10, Python-dateutil 2.7.</p>
                            </details>
                        
                    
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Test">Test</h2>
                            <h3>Coverage: 25%</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                        <table>
                            <thead>
                                <tr>
                                    <th scope="col">Module</th>
                                
                                    <th scope="col">Statements</th>
                                
                                    <th scope="col">Missing</th>
                                
                                    <th scope="col">Excluded</th>
                                
                                    <th scope="col">Coverage</th>
                                
                                </tr>
                            </thead>
                            <tbody>
                                    <tr>
                                        <td><a href="files\0.html">src\pythontemplate\__init__.py</a></td>
                                        <td>0</td>
                                        <td>0</td>
                                        <td>0</td>
                                        <td>100.0 %</td>
                                    </tr>
                                    <tr>
                                        <td><a href="files\1.html">src\pythontemplate\bad_example.py</a></td>
                                        <td>6</td>
                                        <td>6</td>
                                        <td>0</td>
                                        <td>0.0 %</td>
                                    </tr>
                                    <tr>
                                        <td><a href="files\2.html">src\pythontemplate\example_module.py</a></td>
                                        <td>2</td>
                                        <td>0</td>
                                        <td>0</td>
                                        <td>100.0 %</td>
                                    </tr>
                            </tbody>
                        </table>
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Documentation">Documentation</h2>
                            <h3>Coverage: 69%</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <details>
                                <summary><b>Missing description</b>: pythontemplate.bad_example</summary>
                                <p><b>Object</b>: pythontemplate.bad_example<br /><b>File</b>: <a href="files\3.html#1">src\pythontemplate\bad_example.py</a><br /><b>Line</b>: 1<br />The module pythontemplate.bad_example has no description.</p>
                            </details>
                        
                            <details>
                                <summary><b>Undocumented return value</b>: pythontemplate.bad_example.getHash</summary>
                                <p><b>Object</b>: pythontemplate.bad_example.getHash<br /><b>File</b>: <a href="files\4.html#7">src\pythontemplate\bad_example.py</a><br /><b>Line</b>: 7<br />The return value of function pythontemplate.bad_example.getHash is not documented. Note that this message may also have been caused by incorrect indentation.</p>
                            </details>
                        
                            <details>
                                <summary><b>Undocumented parameter</b>: password</summary>
                                <p><b>Object</b>: password<br /><b>File</b>: <a href="files\4.html#7">src\pythontemplate\bad_example.py</a><br /><b>Line</b>: 7<br />Parameter password of function pythontemplate.bad_example.getHash is not documented.</p>
                            </details>
                        
                            <details>
                                <summary><b>Documented but unused parameter</b>: pw</summary>
                                <p><b>Object</b>: pw<br /><b>File</b>: <a href="files\4.html#7">src\pythontemplate\bad_example.py</a><br /><b>Line</b>: 7<br />Parameter pw of function pythontemplate.bad_example.getHash has been documented although it is not part of the function's signature. Note that this may also be a false positive caused by incorrect indentation. This means parameter documentation exceeding a single line needs to be indented by a single tab.</p>
                            </details>
                        
                    
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Dependencies">Dependencies</h2>
                            <h3>Issues: 11</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <h5>Active Environment</h5>
                            <details>
                                <summary><b>django</b> >=3.0a1,<3.2.11</summary>
                                <p><b>ID</b>: 44426<br /><b>Installed</b>: 3.2<br />Django 2.2.26, 3.2.11 and 4.0.1 include a fix for CVE-2021-45452: Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it.
https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.0a1,<3.2.11</summary>
                                <p><b>ID</b>: 44423<br /><b>Installed</b>: 3.2<br />Django 2.2.26, 3.2.11 and 4.0.1 include a fix for CVE-2021-45115: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.
https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.0a1,<3.2.11</summary>
                                <p><b>ID</b>: 44427<br /><b>Installed</b>: 3.2<br />Django 2.2.26, 3.2.11 and 4.0.1 include a fix for CVE-2021-45116: An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language's variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key.
https://www.djangoproject.com/weblog/2022/jan/04/security-releases/</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.0a1,<3.2.12</summary>
                                <p><b>ID</b>: 44741<br /><b>Installed</b>: 3.2<br />An issue was discovered in MultiPartParser in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2. Passing certain inputs to multipart forms could result in an infinite loop when parsing files.</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.0a1,<3.2.12</summary>
                                <p><b>ID</b>: 44742<br /><b>Installed</b>: 3.2<br />The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS.</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2,<3.2.5</summary>
                                <p><b>ID</b>: 40899<br /><b>Installed</b>: 3.2<br />Django versions 3.1.13 and 3.2.5 include a fix for CVE-2021-35042: Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application.
https://www.djangoproject.com/weblog/2021/jul/01/security-releases/
https://www.openwall.com/lists/oss-security/2021/07/02/2
https://docs.djangoproject.com/en/3.2/releases/security/
https://groups.google.com/forum/#%21forum/django-announce</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2.0a1,<3.2.4</summary>
                                <p><b>ID</b>: 40638<br /><b>Installed</b>: 3.2<br />Django 2.2.24, 3.1.12, and 3.2.4 includes a fix for CVE-2021-33571: In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+).
https://www.djangoproject.com/weblog/2021/jun/02/security-releases/</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2a1,<3.2.1</summary>
                                <p><b>ID</b>: 40404<br /><b>Installed</b>: 3.2<br />In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names.</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2a1,<3.2.10</summary>
                                <p><b>ID</b>: 43041<br /><b>Installed</b>: 3.2<br />Django versions 2.2.25, 3.1.14 and 3.2.10 include a fix for CVE-2021-44420: In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.
https://www.djangoproject.com/weblog/2021/dec/07/security-releases/</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2a1,<3.2.2</summary>
                                <p><b>ID</b>: 40414<br /><b>Installed</b>: 3.2<br />Django versions 3.2.2, 3.1.10 and 2.2.22 include a fix for CVE-2021-32052: In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.
https://www.djangoproject.com/weblog/2021/may/06/security-releases</p>
                            </details>
                        
                            <details>
                                <summary><b>django</b> >=3.2a1,<3.2.4</summary>
                                <p><b>ID</b>: 40637<br /><b>Installed</b>: 3.2<br />Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories.
https://www.djangoproject.com/weblog/2021/jun/02/security-releases</p>
                            </details>
                        
                    
                            <hgroup>
                                <h5>setup.cfg</h5>                            
                                <h6>No Issues.</h6>
                            </hgroup>
                    
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Security">Security</h2>
                            <h3>Issues: 2</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <details>
                                <summary><b>blacklist</b>: Consider possible security implications associated with the subprocess module.</summary>
                                <p><b>Test ID</b>: B404<br /><b>Severity</b>: LOW<br /><b>Confidence</b>: HIGH<br /><b>File</b>: <a href="files\5.html#2">src\pythontemplate\bad_example.py</a><br /><b>Line(s)</b>: 2, 3<br /><b>More Information</b>: <a href="https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_imports.html#b404-import-subprocess">https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_imports.html#b404-import-subprocess</a></p>
                            </details>
                        
                            <details>
                                <summary><b>blacklist</b>: Use of insecure MD2, MD4, MD5, or SHA1 hash function.</summary>
                                <p><b>Test ID</b>: B303<br /><b>Severity</b>: MEDIUM<br /><b>Confidence</b>: HIGH<br /><b>File</b>: <a href="files\6.html#15">src\pythontemplate\bad_example.py</a><br /><b>Line(s)</b>: 15<br /><b>More Information</b>: <a href="https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b303-md5">https://bandit.readthedocs.io/en/1.7.4/blacklists/blacklist_calls.html#b303-md5</a></p>
                            </details>
                        
                    
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Style">Style</h2>
                            <h3>Issues: 2</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <h5>src\pythontemplate\bad_example.py</h5>
                            <details>
                                <summary>'subprocess' imported but unused</summary>
                                <p><b>Code</b>: F401<br /><b>Line</b>: 2<br /><b>Column</b>: 1<br /><b>File</b>: <a href="files\7.html#2">src\pythontemplate\bad_example.py</a></p>
                            </details>
                        
                            <details>
                                <summary>'django.db.models.Model' imported but unused</summary>
                                <p><b>Code</b>: F401<br /><b>Line</b>: 4<br /><b>Column</b>: 1<br /><b>File</b>: <a href="files\8.html#4">src\pythontemplate\bad_example.py</a></p>
                            </details>
                        
                    
                            <hgroup>
                                <h5>src\pythontemplate\example_module.py</h5>                            
                                <h6>No Issues.</h6>
                            </hgroup>
                    
                            <hgroup>
                                <h5>src\pythontemplate\__init__.py</h5>                            
                                <h6>No Issues.</h6>
                            </hgroup>
                    
            </article>
            <article>
                <header>
                    <nav>
                        <hgroup>
                            <h2 id="Types">Types</h2>
                            <h3>Issues: 1</h3>
                        </hgroup>
                        <ul>
                                <li><a href="#top">Up</a></li>
                        </ul>
                    </nav>

                </header>
                            <h5>src\pythontemplate\bad_example.py</h5>
                            <details>
                                <summary><b>arg-type</b>: Argument 1 to "getHash" has incompatible type "int"; expected "str"</summary>
                                <p><b>Line</b>: 18<br /><b>Type</b>: Error <br /><b>Code</b>: arg-type <br /><b>File</b>: <a href="files\9.html#18">src\pythontemplate\bad_example.py</a></p>
                            </details>
                        
                    
            </article>
    </main>
  </body>
</html>